- agents/agent_meta_list.go
- particles/particle_list.go
- particles/particle_meta.go
- particles/particle_meta_list.go
- particles/particles.go
Changes:
- fix agent_meta_list
- particles mod created
> More Scaffolding

- go.mod
- go.sum
- main.go
- render/window.go
Changes:
- glfw and gl scaffolding
- window.go
- main.go
> glfw window scaffolding

- main.go
Changes:
- Daco_3555790.png renamed to cat.png
> rename asset name for cat

- README.md
Changes:
.github\images\mingw.png --> .github/images/mingw.png
> Corrected mingw Image link

- .gitignore
- spriteloader/imgloader.go
- spriteloader/spriteloader.go
- spriteloader/stats.go
- test/test-imgloader.go
1.add img loader module
2..gitignore add *.idea
3.add img loader test
4.optimize img stat
5.spriteloader add function AddSpriteSheet 
6.spriteloader fix some function's return value
> add img loader and test

- main.go
- models/cat.go
- physics/physics.go
- spriteloader/spriteloader.go
- world/planet.go
* Cat is drawn using the existing `spriteloader/` library
* Cat is placed using `planet.GetHeight()`
> Fix player spawn

- models/cat.go
- physics/body.go
Closes #90 
* Increased cat size
* Adjusted physics to handle Bodies of non-unit size
> Increase cat size to 2x2

- assets/shader/color.frag
- assets/shader/color.vert
- cxmath/cxmath.go
- item/inventory.go
- item/item.go
- item/worlditem.go
- main.go
- spriteloader/spriteloader.go
- utility/colorshader.go
- world/devplanet.go
> Add inventory

- item/item.go
- item/worlditem.go
- main.go
- stats/stats.go
- stats/stats_test.go
closes #21 
Not connected to anything but at the moment but functionality can be found in `stats/stats_test.go`
> add stats collection system

- camera/camera.go
- camera/frustum.go
- cmd/starfield/main.go
- main.go
- render/window.go
- spriteloader/spriteloader.go
- ui/text.go
- utility/lerp.go
https://user-images.githubusercontent.com/5618012/119901679-bf626280-bf35-11eb-97b0-1a1988948aeb.mp4
> added zoom

- camera/camera.go
- cmd/starfield/config/star.yaml
- cmd/starfield/main.go
- main.go
- render/window.go
- spriteloader/spriteloader.go
- test/test-animation-model.go
- test/test-blackcat-spriteloader.go
- test/test-dialogwindow.go
- test/test-lerp.go
- test/test-spriteloader.go
- test/test-zoom.go
- ui/dialogue.go
- ui/text.go
- utility/interpolation.go
- utility/lerp.go
- utility/makevao.go
- utility/radians.go
- utility/texture.go
there is still issue with objects dissappearing after zooming in, will find  the issue and fix it later
> fixed draw on dialogues and drawing lines

- main.go
- render/window.go
- ui/text.go
- ui/tile-palette-selector.go
- world/planet.go
- world/tile.go
> support multi-tile placement

- cxmath/cxmath.go
- item/lasergun.go
- main.go
- models/player.go
- physics/body.go
- world/planet.go
Also fixes some rendering discrepancies
> add rudimentary planet wrap around behavior

- README.md
Solves `Cannot find <alsa/asoundlib.h>`
> add missing dependency

- camera/camera.go
- cmd/starfield/main.go
- models/player.go
- physics/body.go
- physics/collisioninfo.go
- sound/sound.go
- utility/clamp.go
- utility/functions.go
- utility/interpolation.go
changed jump to happen only if collision with the floor occurs. Restructured camera zoom in a way to easily play with zoom levels
> changed jump

- item/inventory.go
- item/item.go
- item/lasergun.go
- item/worlditem.go
- main.go
- world/generate.go
- world/planet.go
> add mining and building

- cxmath/math32/math32.go
- models/player.go
> player display flips based on movement direction

- camera/frustum.go
- world/generate.go
- world/planet.go
> generate walls along with terrain

- cxmath/vec.go
- enemies/enemies.go
- enemies/pathfinding/leaping.go
- enemies/pathfinding/pathfinding.go
- enemies/pathfinding/walking.go
- enemies/slime.go
- game/init.go
- models/player.go
closes #216 
* Separate pathfinding behaviour from enemy implementation
* Add walking / leaping enemies
Apply leaping animation to slime enemy once animated sprites are implemented
> add different pathfinding behaviours

- assets/shader/nineslice.frag
- assets/shader/nineslice.vert
- render/geometry.go
- ui/hud.go
- ui/nineslice.go
> implement proper hp bar with 9slice logic in shader

- assets/shader/arc.frag
- ui/arc.go
- ui/hud.go
> Fix circle padding

- enemies/enemies.go
- enemies/pathfinding/free.go
- physics/collision.go
add free pathfinding behaviour for dead enemies
add extra bullet collision checks
> Check bullet collisions more rigorously and adjust dead enemy physics

- world/autoplacer.go
- world/tiletypes.go
> auto-tiler accepts multiple spritesheets

- assets/shader/sprite.vert
- test/benchmarks/slice_append_test.go
added simple benchmark to see which way of appending to slice is best.
> added benchmark

- .gitignore
- assets/shader/world.vert
- camera/camera.go
- camera/frustum.go
- cxmath/frustum.go
- cxmath/mathi/mathi.go
- main.go
- render/shader.go
- spriteloader/spriteloader.go
- starfield/starfield.go
- ui/tile-palette-selector.go
- world/devplanet.go
- world/draw.go
- world/mapgen/generate.go
- world/planet.go
- world/tiletype.go
- z_game/game/draw.go
- z_game/game/glfw_callbacks.go
On my laptop, these changes boost fps from ~26 to ~60
- remove unecessary OpenGL calls
- do less work during starfield draw
- rename layer type to LayerID
- Use instancing for rendering world tiles
- move frustum type to cxmath package
- add package for int64 math
- add separate file for rendering planet
> Optimize rendering

- components/particles/particle_draw/draw_transparent.go
- z_game/game/draw.go
> fixed projection

- components/particles/particle_draw/draw_transparent.go
- components/particles/particle_draw/drawhandlerlist.go
- components/particles/particle_emitter/particleemitter.go
- components/particles/particlelist.go
- physics/body.go
added temporary bounce variables to physics/body.go.
> add bounce

- components/particles/particle.go
- components/particles/particle_draw/draw_solid.go
- components/particles/particle_draw/particles_draw.go
- components/particles/particle_emitter/particleemitter.go
- components/particles/particle_physics/physicshandler_1.go
- components/particles/particle_physics/physicshandler_2.go
- components/particles/particle_physics/physicshandler_3.go
- components/particles/particlebody.go
- components/particles/particlelist.go
- components/update.go
- physics/body.go
added physics handler specific to particles only (almost a copypaste of physics/body.go, but allows for fewer fields and different physics options)
> added physics handlers

- components/agents/agent_ai/drilling.go
- events/spiderdrill_event.go
- objects/slime.go
- objects/spiderdrill.go
implement event listener to a game object, specific purposes to animated sprite. 
so extending object behavior will be easier, because it will be separated from low-level code such as OpenGL drawing
> implement event listener to game object

- engine/ui/console/command.go
- engine/ui/console/console.go
> add help command and display command output in console

- components/agents/agent_ai/agent_ai.go
- components/agents/agent_ai/player.go
- components/agents/agents.go
- world/tiletypes.go
> Fix platform

- engine/camera/camera.go
> increase zoom speed

- components/agents/agent_draw/player.go
- components/agents/types.go
- constants/agents.go
> Reduce player hitbox size

- components/agents/agent_ai/player.go
- engine/camera/camera.go
- engine/input/input.go
- game/processinput.go
bind f2 key to see different zoom levels
> zoom levels

- components/agents/agent_ai/player.go
- engine/input/input.go
- engine/spriteloader/spriteloader.go
- game/processinput.go
- render/gltex.go
- render/sprite-draw.go
- render/sprites.go
F6 to toggle filtering  to see different result on zoom in/out
> added toggle filtering

- assets/shader/particles/blended_instanced.vert
- components/particles/particle_draw/draw_transparent.go
- components/particles/particle_draw/drawhandlerlist.go
- components/particles/particle_draw/particles_draw.go
- constants/render.go
- cxmath/math32/math32.go
- engine/camera/camera.go
- game/draw.go
- item/inventory.go
- item/placement-grid.go
- render/sprite-draw.go
closes #316 
- UI does not zoom with world
- mouse coordinates scale correctly when converted to world coordinates
> Fix UI zoom

- render/window.go
mouse was not working properly because it was waiting on resize callback to adjust the window dimensions, so i added code to manually "trigger" callback
> fixed mouse

- components/agents/agent_ai/player.go
- engine/camera/camera.go
- engine/input/input.go
- engine/input/interface.go
- engine/input/keyboard.go
- engine/ui/console/command.go
- engine/ui/console/console.go
- game/glfw_callbacks.go
- game/processinput.go
added input context (for when in console mode, freecam mode, or game mode, so same keys can be used for different actions depending on game state)
tweaked jump and sliding a bit
> tweaked jump and sliding

- assets/shader/particles/blended.vert
- assets/shader/particles/solid.vert
- components/particles/particle_draw/draw_solid.go
- components/particles/particle_draw/draw_transparent.go
- engine/camera/camera.go
- particle_emitter/sparkemitter.go
-fixed bug where zoom would go in reverse
-added view matrix to the solid particle draw
> fixed view matrix on particles

- engine/camera/camera.go
- engine/ui/console/command.go
- engine/ui/console/context.go
- game/update.go
- render/sprite-draw.go
closes #331 and #315
- Add teleport command
- Include player in command context
- Wrap camera X relative to world
> Fix player wrap

- item/placement-grid.go
> highlight border of selected tile in placement grid

- constants/agents.go
- physics/body.go
- world/draw.go
> agents wrap around vertically

- components/agents/agent_ai/agent_ai.go
- components/agents/agent_ai/aihandler.go
- components/agents/agent_ai/drilling.go
- components/agents/agent_ai/leap.go
- components/agents/agent_draw/animated.go
- objects/spiderdrill.go
-also fixed pathfinding on agents
-and the case where spider drill would swap its direction each tick causing visible glitch
> fixed wraparound render on agents

- assets/shader/line.vert
- components/agents/agent_draw/agent_draw.go
- engine/camera/camera.go
- engine/input/input.go
- engine/sound/sound.go
- game/draw.go
- game/processinput.go
- render/bbox.go
- render/lines.go
- render/sprite-draw.go
added bbox toggle on agents when pressing F1 key
> added bbox toggle

- components/agents/agent_ai/player.go
> player falls through one platform only

- item/placement-grid.go
> Fix wall placement

- constants/agents.go
- physics/body.go
- world/planet.go
> clamp agents to height limit

- render/window.go
> add FixRenderCOCOA

- components/agents/agents_list.go
- physics/body.go
> fix collision detection for tile placement

- assets/shader/spritesheet.vert
- assets/shader/spritesheetv2.frag
- assets/shader/spritesheetv2.vert
- assets/shader/spritesheetv3.frag
- assets/shader/spritesheetv3.vert
- engine/camera/camera.go
- engine/input/input.go
- engine/input/interface.go
- engine/input/keyboard.go
- game/processinput.go
- game/update.go
- render/sprite-draw.go
- render/sprite.go
divided `modelviews` uniform to `model` and `view` for easier pixel rounding calculation
> pixel snapping

- game/init.go
for render.FixRenderCOCOA(window)
> add runtime.GOOS == "darwin"

- components/agents/agent_ai/player.go
- engine/input/input.go
- engine/input/interface.go
- engine/input/keyboard.go
- engine/input/mouse.go
- game/glfw_callbacks.go
- game/init.go
If holding "down" button, it will fall until key is pressed up
> change player fall behaviour on platforms

- constants/tile.go
- item/dev-inventory.go
- item/register.go
- item/tool.go
- item/tooltype.go
- world/tiletypes.go
> add placement tool for background tiles

- item/placement-grid.go
- world/world.go
> only check agent collisions for top layer tiles

- components/agents/agent_ai/leap.go
- game/init.go
- render/window.go
> fix slime behavior 

- engine/input/input.go
- engine/log.go
- game/processinput.go
> F10 toggles all logging

- engine/camera/camera.go
- engine/camera/frustum.go
- engine/input/keyboard.go
fixed broken frustum check logic
> Fixed frustum

- components/agents/agent_ai/drilling.go
- components/agents/agent_ai/leap.go
- item/gun.go
- item/lasergun.go
- world/planet.go
> slime behaviour and spider effect to tile

- components/particles/particle_draw/draw_solid.go
- components/particles/particle_draw/draw_transparent.go
- components/update.go
- engine/camera/camera.go
- engine/camera/frustum.go
- engine/camera/window.go
- engine/camera/zoom.go
- engine/input/input.go
- game/draw.go
- game/glfw_callbacks.go
- game/processinput.go
- game/update.go
- render/context.go
- render/lines.go
- render/window.go
- render/worldctx/worldctx.go
- world/draw.go
-added target camera
-cleaned up code
-separated zoom code
> Camera centered on player

- cxmath/math32/math32.go
- engine/ui/damage.go
closes #456 
https://user-images.githubusercontent.com/8276517/133465777-ef3566ab-06f3-4a39-94cc-a0db703f49a6.mp4
> Damage text enhance

- cxmath/math32/math32.go
- engine/camera/frustum.go
- engine/camera/zoom.go
- engine/spriteloader/spriteloader.go
- engine/spriteloader/upload.go
- game/update.go
- render/gltex.go
- render/sprite-draw.go
-fixed small sprite draw bug
-adjusted frustum
> fixed sprite draw

- assets/shader/quad.frag
- assets/shader/quad.vert
- engine/camera/frustum.go
- engine/spriteloader/config.go
- game/draw.go
- render/sprite.go
- world/init.go
- world/lighting.go
-add smooth lighting
-revert texture drawing method back
> add smooth lighting

- world/tiling/full.go
> adjust auto-tiling behaviour

- engine/camera/camera.go
- engine/camera/shake.go
- game/processinput.go
simple screen shake option, bind to B key.
> added screen shake

- assets/tile/furnitures.yaml
- assets/tile/tables.yaml
- item/placement-grid.go
- world/autoplacer.go
- world/tile.go
- world/tiletype.go
- world/tiletypes.go
- add "needsground" field to tile config
- furniture can only be placed on ground
- refactor placement grid check
> Furniture can only be placed on ground

- game/draw.go
- render/sprite-draw.go
> outline zooms

- constants/render.go
- render/sprite-draw.go
> thicken and darken outline

- constants/render.go
- game/draw.go
- render/sprite-draw.go
- world/draw.go
- world/layer.go
> Add super-imposed layer for fluids
